---
title: "salt_marsh_work"
author: "emily"
date: "2025-06-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r reading data}
library(readr)
library(ggplot2)
library(sf)
library(stars)
library (dplyr)
library(tidyverse)

#adding ranodm thing

buffer<-3

```

```{r}
poly_OTH<- read_csv("Labeled Data/Poly/LabeledData_OTH_27Jul2023_Poly.csv")

poly_OTH_sf<- st_as_sf(poly_OTH, coords = c("Northing", "Easting"), crs = 26919)|>
   group_by(PolygonNum)|>
   dplyr::summarize(do_union=FALSE)|>
   st_cast("POLYGON")
  
poly_oth_buf_sf<- st_buffer(poly_OTH_sf, buffer)

ggplot()+
   geom_sf(data = poly_oth_buf_sf)
```

```{r}
poly_PEG_6oct<- read_csv("Labeled Data/Poly/LabeledData_PEG_06oct2018_Poly.csv")
poly_PEG_07oct<- read_csv("Labeled Data/Poly/LabeledData_PEG_07oct2018_Poly.csv")


poly_PEG_6oc_sf<- st_as_sf(poly_PEG_6oct, coords = c("Northing", "Easting"), crs = 26919)|>
   group_by(PolygongonNum)|>
   dplyr::summarize(do_union=FALSE)|>
   st_cast("POLYGON")

poly_PEG_7oc_sf<- st_as_sf(poly_PEG_07oct, coords = c("Northing", "Easting"), crs = 26919)|>
   group_by(PolygongonNum)|>
   dplyr::summarize(do_union=FALSE)|>
   st_cast("POLYGON")

  
poly_peg6oct_buf_sf<- st_buffer(poly_PEG_6oc_sf, buffer)
poly_peg7oct_buf_sf<- st_buffer(poly_PEG_7oc_sf, buffer)

ggplot()+
   geom_sf(data = poly_peg6oct_buf_sf, aes(fill = "6"))+
   geom_sf(data = poly_peg7oct_buf_sf, aes(fill = "7"))
   
```


```{r}
points_sf<- st_as_sf(points, coords = c("Easting", "Northing"), crs=26919)|>

points_buf<- st_buffer(points_sf, buffer)

ggplot()+
   geom_sf(data = points_buf)
```

```{r}
lines<-filter(field_points, SampFormat == "line") 

lines_sf<- st_as_sf(lines, coords = c("Easting", "Northing"), crs=26919)|>
   group_by(SampFormat)|>
   dplyr::summarize(do_union=FALSE)|>
   st_cast("LINESTRING")

ggplot() + geom_sf(data=lines_sf)

```

```{r}
class06_points<- filter(points, Subclass == "06")

class06_points_sf<- st_as_sf(class06_points, coords = c("Easting", "Northing"), crs=26919)|>
   group_by(Subclass)|>
   dplyr::summarize(do_union=FALSE)|>
   st_cast("POLYGON")

st_write(class06_points_sf, "06_poly.shp")

ggplot()+
   geom_sf(data = class06_points_sf)
```

```{r}
lines_buf<- st_buffer(lines_sf, buffer)

ggplot()+
   geom_sf(data = lines_buf)
```

```{r}
poly_sf<- st_as_sf(lines, coords = c("Easting", "Northing"), crs=26919)|>
   group_by(SampFormat)|>
   dplyr::summarize(do_union=FALSE)|>
   st_cast("POLYGON")

ggplot()+
   geom_sf(data = poly_sf)
```

```{r}
poly_sf<- st_as_sf(lines, coords = c("Easting", "Northing"), crs=26919)|>
   group_by(SampFormat)|>
   dplyr::summarize(do_union=FALSE)|>
   st_cast("POLYGON")

st_write(poly_sf, "all_points_poly.shp")

ggplot()+
   geom_sf(data = poly_sf, aes(fill = "all" ))+
   geom_sf(data = class06_points_sf, aes(fill = "06 class"))
  
```
```{r}
#Still working on, trying to clip the two polygons

all_points_shape<-st_read ("all poly files/all_points_poly.shp")
class06_shape<- st_read("06 poly files/06_poly.shp")

all_points_shape<-st_make_valid(all_points_shape)
class06_shape<- st_make_valid(class06_shape)

clip<- st_intersection(class06_shape, all_points_shape)

ggplot()+
   geom_sf(data = clip, fill = "06")

```
 
 